name: 'Dotfiles on MacOS'

on: # -- Controls when the action will run. Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: # -- A workflow run is made up of one or more jobs that can run sequentially or in parallel
  dotfiles: # -- This workflow job
    runs-on: macos-latest # -- The type of runner that the job will run on
    defaults:
      run:
        shell: bash # -- Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest

    steps: # -- Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dotfiles
      run: ./install